main: ${mainClassName}
name: SignEdit
author: Deltik
version: ${pluginVersion}
description: Edit a sign by looking at it
commands:
  sign:
    description: Edit the sign you are looking at
  signedit:
    description: Alias for /sign
  editsign:
    description: Alias for /sign
  se:
    description: Alias for /sign
