main: ${mainClassName}
name: SignEdit
author: Deltik
version: ${pluginVersion}
description: Edit a line in an existing sign
commands:
  sign:
    description: Set or clear the line in the sign
    usage: /<command> [{set,clear}] <line> [<text>]
    permission: SignEdit.use
  signedit:
    description: Alias for /sign
  editsign:
    description: Alias for /sign
  se:
    description: Alias for /sign
