main: org.deltik.mc.SignEdit.Main
name: SignEdit
author: Deltik
version: 1.4.0
description: Edit a sign by looking at it
commands:
  sign:
    description: Edit the sign you are looking at
  signedit:
    description: Alias for /sign
  editsign:
    description: Alias for /sign
  se:
    description: Alias for /sign
